version: '3.1'

services:

  api:
    build: .
    links: 
      - database
    ports:
      - 8000:8000

  database:
    image: mysql
    env_file:
      - config/mysql.env
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080