version: '3.1'

services:

  api:
    build: .
    links: 
      - database
    ports:
      - 8000:8000

  database:
    image: postgres:13.1
    env_file:
      - config/postgres.env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080