version: '3.1'

services:

  api:
    build: .
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - database
    links: 
      - rabbitmq
      - database
    ports:
      - 8000:8000

  database:
    image: postgres:13.1
    env_file:
      - config/postgres.env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080

  rabbitmq:
    image: rabbitmq
    env_file:
      - config/rabbitmq.env
    ports:
      - 5672:5672