"""create history table

Revision ID: 6e68e0e569fc
Revises: ef8826814e36
Create Date: 2023-07-19 21:04:02.391684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e68e0e569fc'
down_revision = 'ef8826814e36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
